# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [4]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x23e6db08930
byteorder:  little
byteswap:  False
type: int32


In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.6707764  0.21829835 0.22976652]
 [0.16897297 0.14857843 0.28016849]
 [0.12086824 0.27720593 0.48951363]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [10]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.6707764  0.21829835 0.22976652]
 [0.16897297 0.14857843 0.28016849]
 [0.12086824 0.27720593 0.48951363]]
...
float64
(3, 3)
3
2
9
8
72


In [11]:
arr.__sizeof__()

184

### ЗАВДАННЯ 1

In [12]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 =np.random.rand(3,4)
print(arr1_1,arr1_1.dtype)

[[0.96089362 0.76866678 0.61283022 0.03461065]
 [0.6300705  0.88919026 0.40396005 0.28822679]
 [0.21390991 0.84617461 0.85352028 0.11803396]] float64


In [13]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array([1,2,3,4,5])
print(arr1_2)

[1 2 3 4 5]


In [14]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 =np.ones((3,4))
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [15]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [17]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [18]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [19]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 =np.full((3,1,3),False)

print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [21]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 =arr2_1.reshape((3,3)).astype("int")
print(arr2_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [22]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 =np.arange(10,21,2)
print(arr2_3)

[10 12 14 16 18 20]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [ ]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

In [ ]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

In [ ]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, 2]
print(el)

In [ ]:
# отримати значення останнього рядка
vect = arr[2]
print(vect)

In [ ]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

In [ ]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

In [ ]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

In [ ]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

### ЗАВДАННЯ 3

In [23]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 =np.random.randint(10,100,(4,5))
arr3_1

array([[78, 50, 16, 37, 51],
       [77, 81, 34, 57, 85],
       [54, 24, 77, 64, 46],
       [57, 67, 84, 41, 89]])

In [24]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1,2]
print(el3_2)

34


In [25]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 =arr3_1[1]
print(vect3_3)

[77 81 34 57 85]


In [26]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 =arr3_1[0:4,2]
print(vect3_4)

[16 34 77 84]


In [27]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3,1:3]
print(mat3_5)

[[81 34]
 [24 77]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [29]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

In [ ]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

In [ ]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

In [ ]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

In [ ]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

### ЗАВАДАННЯ 4

In [33]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.random.randint(100, 200, (6,6))
print(mat4_1)

[[132 199 167 144 196 130]
 [119 133 103 121 178 182]
 [139 120 116 117 189 127]
 [112 129 131 135 120 130]
 [178 127 142 115 184 196]
 [140 186 132 109 112 167]]


In [34]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 =np.diag(mat4_1)
print(diag4_2)

[132 133 116 135 184 167]


In [36]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 =np.linalg.inv(mat4_1)
inv4_4

array([[-0.01830458, -0.01520988,  0.0307216 , -0.00029044, -0.00642303,
         0.01522649],
       [ 0.00095727,  0.00169365,  0.00683763, -0.00888256, -0.0117478 ,
         0.01291158],
       [ 0.02344729, -0.00710636, -0.03566789,  0.00389066,  0.02705425,
        -0.018164  ],
       [-0.01704072,  0.00178878,  0.02032371,  0.02100982, -0.01989213,
         0.00285153],
       [ 0.00800457,  0.005597  ,  0.00010612, -0.00923111,  0.00205109,
        -0.0076329 ],
       [ 0.00149985,  0.01156026, -0.01851395, -0.0004607 ,  0.00869266,
        -0.0035422 ]])

In [ ]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = ...

## 5. Операції над масивами

### ПРИКЛАДИ

In [ ]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [ ]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

In [ ]:
# матриця 3х4 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

In [ ]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

In [ ]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

In [ ]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

In [ ]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

In [ ]:
# поелементний поділ
K = N / M
print(K)

In [ ]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

In [ ]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

In [ ]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

In [ ]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

In [ ]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

In [ ]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

In [ ]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

### ЗАВДАННЯ 5

In [37]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.rand(3,4)
sum_mat5_1 = np.sum(mat5_1,axis=1)
print(sum_mat5_1)

[1.83267247 2.53578597 1.51503844]


In [38]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(sum_mat5_1)
print(min_mat5_1)

1.5150384362174432


In [39]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1+100
print(mat5_3)

[[100.28640955 100.7102598  100.32951578 100.50648735]
 [100.75186467 100.94614002 100.4123874  100.42539388]
 [100.30133546 100.38043626 100.08641476 100.74685195]]


In [40]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_4 = np.dot(np.diag(mat5_3),mat5_1)
print(mat5_4)

[134.78040753 204.81508917  83.32381414 168.48540193]


In [41]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.row_stack((mat5_3, mat5_4))
np.linalg.matrix_rank(mat5_5)

4